#!/usr/bin/env bash

DEFAULT_AVD_PATH=~/.android/avd

function run_sed {
    if [ "$(uname)" == "Darwin" ]; then
        # macOS requires extra argument for -i param
        sed -i '' $1 $2
    else
        sed -i $1 $2
    fi
}

# Use provided path by user or fallback to the default one
avd_path=${1:-$DEFAULT_AVD_PATH}
# Remove trailing slash if present
avd_path=${avd_path%/}
echo "🔊 Processing emulators from: $avd_path"

for emulator in $(find $avd_path -type d -name '*.avd'); do   
    if [ ! -f $emulator/config.ini ]; then
        echo "❌ Skipping emulator - could not config.ini inside $emulator"
        continue
    fi
    echo "🔊 Processing - $(basename $emulator)"

    # Remove line hw.audioInput - if exists
    run_sed '/^hw.audioInput/d' $emulator/config.ini
    
    # Remove line hw.audioOutput - if exists
    run_sed '/^hw.audioOutput/d' $emulator/config.ini
    
    # Disable audio input and output
    echo "hw.audioInput=no" >> $emulator/config.ini
    echo "hw.audioOutput=no" >> $emulator/config.ini

    # Sort config keys
    sort -o $emulator/config.ini $emulator/config.ini

    echo "✅ Done - $(basename $emulator)"
done